name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the action

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your preferred region

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Create ECR repositories (if they don't exist)
      - name: Create ECR Repositories
        run: |
          aws ecr describe-repositories --repository-names patient-service|| \
            aws ecr create-repository --repository-name patient-service
          aws ecr describe-repositories --repository-names appointment-service || \
            aws ecr create-repository --repository-name appointment-service

      # Step 5: Build Docker images for microservices
      - name: Build Docker image for microservice1
        run: |
          docker build -t patient-service ./app/patient  # Assuming Dockerfile is in the `microservice1` folder
          
      - name: Build Docker image for microservice2
        run: |
          docker build -t appointment-service ./app/appointment  # Assuming Dockerfile is in the `microservice2` folder

      # Step 6: Tag and push Docker images to ECR
      - name: Push Docker image for microservice1
        run: |
          ECR_URI=$(aws ecr describe-repositories --repository-name patient-service --query 'repositories[0].repositoryUri' --output text)
          docker tag patient-service:latest $ECR_URI:latest
          docker push $ECR_URI:latest

      - name: Push Docker image for microservice2
        run: |
          ECR_URI=$(aws ecr describe-repositories --repository-name appointment-service --query 'repositories[0].repositoryUri' --output text)
          docker tag appointment-service:latest $ECR_URI:latest
          docker push $ECR_URI:latest
