name: Build and Push to ECR Registery

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (e.g., dev, staging, prod)"
        required: true
        type: string

env:
  AWS_REGION: "us-east-1" # Replace with your AWS region
  TF_VERSION: "1.5.7"    # Replace with your desired Terraform version
  ECR_REPOSITORY: "dev-ecr" # Replace with your ECR repository name

jobs:
  terraform:
    name: "Terraform Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Required for private repositories
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
               
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build and Push Appointment App
        run: |
          cd app/appointment
          docker build -t appointment-app:${{ github.sha }} .
          docker tag appointment-app:${{ github.sha }} \
            664418994073.dkr.ecr.us-east-1.amazonaws.com/dev-ecr:appointment-app-${{ github.sha }}
          docker push 664418994073.dkr.ecr.us-east-1.amazonaws.com/dev-ecr:appointment-app-${{ github.sha }}

      - name: Build and Push Patient App
        run: |
          cd app/patient
          docker build -t patient-app:${{ github.sha }} .
          docker tag patient-app:${{ github.sha }} \
            664418994073.dkr.ecr.us-east-1.amazonaws.com/dev-ecr:patient-app-${{ github.sha }}
          docker push 664418994073.dkr.ecr.us-east-1.amazonaws.com/dev-ecr:patient-app-${{ github.sha }}
